nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Disposition']
        max_age: 3600
        hosts: []
        origin_regex: false
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH']