security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            stateless: true
            form_login:
                check_path: /api/login
                username_parameter: email
                password_parameter: password
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: /api/logout
                invalidate_session: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 jours
                path: /

#            session: false


    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: PUBLIC_ACCESS }
#        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }